import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`font-hibiscus bg-[#F4F5F7] text-[#65748D] leading-[1.4] bg-[length:40px_40px] bg-[radial-gradient(circle,rgba(101,116,141,0.46)_1px,rgba(0,0,0,0)_1px)]`}>
        {children}
      </body>
    </html>
  );
}
